db:
  database: auth_microservice
  host: localhost
  port: 5432
  adapter: postgresql
  url: <%= ENV['AUTH_DATABASE_URL'] %>
application:
  jwt_secure_code: random_key
  name: auth
logger:
  path: log/app.log
  level: info